Repository Team-BBANGZIP/BBANGZIP-ANDROID, pull requests merged in 2025-05, with the labels that each got.

#5 [INIT] Typography 기초 세팅
  app/src/main/java/org/android/bbangzip/ui/theme/BbangZipTheme.kt
  app/src/main/java/org/android/bbangzip/ui/theme/Theme.kt
  app/src/main/java/org/android/bbangzip/ui/theme/Type.kt
  app/src/main/res/font/pretendard_extrabold.ttf
  app/src/main/res/font/pretendard_medium.ttf
  app/src/main/res/font/pretendard_regular.ttf
  app/src/main/res/font/pretendard_semibold.ttf
Labels: 🩶INIT🩶, 🐰지은🐰

#7 [INIT] Color 기초 세팅
  app/src/main/java/org/android/bbangzip/ui/theme/BbangZipTheme.kt
  app/src/main/java/org/android/bbangzip/ui/theme/Brush.kt
  app/src/main/java/org/android/bbangzip/ui/theme/Color.kt
  app/src/main/java/org/android/bbangzip/ui/theme/Opacity.kt
  app/src/main/java/org/android/bbangzip/ui/theme/Theme.kt
Labels: 🩶INIT🩶, 🐰지은🐰

#10 [INIT] Bottom Navigation 기초세팅
  app/src/main/java/org/android/bbangzip/presentation/type/BottomNavigationType.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/friend/FriendRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/friend/navigation/FriendNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/my/MyRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/my/navigation/MyNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainNavHost.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainNavigator.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/component/BottomNavigationBar.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/timer/TimerRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/timer/navigation/TimerNavigation.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/TodoRoute.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/todo/navigation/TodoNavigation.kt
  app/src/main/java/org/android/bbangzip/ui/theme/Color.kt
  app/src/main/res/drawable/ic_book_default_24.xml
  app/src/main/res/drawable/ic_bubble_default_24.xml
  app/src/main/res/drawable/ic_person_default_24.xml
  app/src/main/res/drawable/ic_timer_default_24.xml
  app/src/main/res/values/strings.xml
Labels: 🩶INIT🩶, 🐯승범🐯

#9 [INIT] 아이콘 기초 세팅
  app/src/main/java/org/android/bbangzip/presentation/ui/dummy/DummyScreen.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainActivity.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/navigator/MainNavHost.kt
  app/src/main/java/org/android/bbangzip/presentation/ui/timer/TimerRoute.kt
  app/src/main/res/drawable/ic_again_default_24.xml
  app/src/main/res/drawable/ic_arrow_left_24.xml
  app/src/main/res/drawable/ic_arrow_right_24.xml
  app/src/main/res/drawable/ic_bell_default_24.xml
  app/src/main/res/drawable/ic_bread_default_24.xml
  app/src/main/res/drawable/ic_calendar_default_24.xml
  app/src/main/res/drawable/ic_check_circled_24.xml
  app/src/main/res/drawable/ic_check_default_24.xml
  app/src/main/res/drawable/ic_clock_default_24.xml
  app/src/main/res/drawable/ic_dot_default_24.xml
  app/src/main/res/drawable/ic_duplicate_default_24.xml
  app/src/main/res/drawable/ic_eye_default_24.xml
  app/src/main/res/drawable/ic_hamburger_menu_default_24.xml
  app/src/main/res/drawable/ic_meatball_menu_default_24.xml
  app/src/main/res/drawable/ic_move_back_default_24.xml
  app/src/main/res/drawable/ic_palette_default_24.xml
  app/src/main/res/drawable/ic_pause_default_80.xml
  app/src/main/res/drawable/ic_pencil_default_24.xml
  app/src/main/res/drawable/ic_plus_bold_24.xml
  app/src/main/res/drawable/ic_plus_default_24.xml
  app/src/main/res/drawable/ic_return_default_24.xml
  app/src/main/res/drawable/ic_return_thin_24.xml
  app/src/main/res/drawable/ic_start_default_80.xml
  app/src/main/res/drawable/ic_stop_default_24.xml
  app/src/main/res/drawable/ic_trash_default_24.xml
  app/src/main/res/drawable/ic_triangle_down_24.xml
  app/src/main/res/drawable/ic_x_default_24.xml
Labels: 🩶INIT🩶, 🦁재민🦁
